name: Build & Attach Release Artifacts

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      mvn_version: ${{ steps.mvn_version.outputs.mvn_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
          java-package: jdk+fx

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Extract Maven version
        id: mvn_version
        run: |
          version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "mvn_version=$version" >> $GITHUB_OUTPUT

      - name: Build JAR
        run: mvn -B clean package

      - name: Copy and rename JAR
        run: |
          cp target/xaml-sorter-java-${{ steps.mvn_version.outputs.mvn_version }}.jar \
          xamlSorter.Java-${{ steps.mvn_version.outputs.mvn_version }}.jar

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: xamlSorter.Java-jar
          path: xamlSorter.Java-${{ steps.mvn_version.outputs.mvn_version }}.jar

  # ------- JPackage jobs ---------
  package-windows:
    runs-on: windows-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: xamlSorter.Java-jar
          path: ./app

      - name: Set up JDK (for jpackage)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
          java-package: jdk+fx

      - name: Package with jpackage (Windows)
        run: |
          jpackage ^
            --type app-image ^
            --name xamlSorter.Java ^
            --input app ^
            --main-jar xamlSorter.Java-${{ needs.build.outputs.mvn_version }}.jar ^
            --main-class chiloven.xamlsorter.Main ^
            --dest dist ^
            --icon src/main/resources/assets/icons/application/application-ico.ico ^
            --java-options "--enable-native-access=ALL-UNNAMED"
        shell: cmd

      - name: Zip Windows app-image
        run: |
          powershell Compress-Archive -Path dist\xamlSorter.Java\* -DestinationPath xamlSorter.Java-${{ needs.build.outputs.mvn_version }}-windows.zip

      - name: Upload Windows zip
        uses: actions/upload-artifact@v4
        with:
          name: xamlSorter.Java-windows-zip
          path: xamlSorter.Java-${{ needs.build.outputs.mvn_version }}-windows.zip

  package-linux:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: xamlSorter.Java-jar
          path: ./app

      - name: Install jpackage dependencies
        run: sudo apt-get update && sudo apt-get install -y libfreetype6 libfontconfig1

      - name: Set up JDK (for jpackage)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
          java-package: jdk+fx

      - name: Package with jpackage (Linux)
        run: |
          jpackage \
            --type app-image \
            --name xamlSorter.Java \
            --input app \
            --main-jar xamlSorter.Java-${{ needs.build.outputs.mvn_version }}.jar \
            --main-class chiloven.xamlsorter.Main \
            --dest dist \
            --icon src/main/resources/assets/icons/application/application-256x256.png \
            --java-options "--enable-native-access=ALL-UNNAMED"

      - name: Zip Linux app-image
        run: |
          cd dist && zip -r ../xamlSorter.Java-${{ needs.build.outputs.mvn_version }}-linux.zip xamlSorter.Java

      - name: Upload Linux zip
        uses: actions/upload-artifact@v4
        with:
          name: xamlSorter.Java-linux-zip
          path: xamlSorter.Java-${{ needs.build.outputs.mvn_version }}-linux.zip

  package-macos:
    runs-on: macos-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: xamlSorter.Java-jar
          path: ./app

      - name: Set up JDK (for jpackage)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
          java-package: jdk+fx

      - name: Package with jpackage (macOS)
        run: |
          jpackage \
            --type app-image \
            --name xamlSorter.Java \
            --input app \
            --main-jar xamlSorter.Java-${{ needs.build.outputs.mvn_version }}.jar \
            --main-class chiloven.xamlsorter.Main \
            --dest dist \
            --icon src/main/resources/assets/icons/application/application-icns.icns \
            --java-options "--enable-native-access=ALL-UNNAMED"

      - name: Zip macOS app-image
        run: |
          cd dist
          zip -r ../xamlSorter.Java-${{ needs.build.outputs.mvn_version }}-macos.zip xamlSorter.Java.app

      - name: Upload macOS zip
        uses: actions/upload-artifact@v4
        with:
          name: xamlSorter.Java-macos-zip
          path: xamlSorter.Java-${{ needs.build.outputs.mvn_version }}-macos.zip

  release:
    needs: [build, package-windows, package-linux, package-macos]
    runs-on: ubuntu-latest
    steps:
      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: xamlSorter.Java-jar
          path: ./artifact

      - name: Download Windows Zip
        uses: actions/download-artifact@v4
        with:
          name: xamlSorter.Java-windows-zip
          path: ./artifact

      - name: Download Linux Zip
        uses: actions/download-artifact@v4
        with:
          name: xamlSorter.Java-linux-zip
          path: ./artifact

      - name: Download macOS Zip
        uses: actions/download-artifact@v4
        with:
          name: xamlSorter.Java-macos-zip
          path: ./artifact

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2.3.2
        with:
          files: |
            artifact/xamlSorter.Java-*.jar
            artifact/xamlSorter.Java-*-windows.zip
            artifact/xamlSorter.Java-*-linux.zip
            artifact/xamlSorter.Java-*-macos.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
